spring:
  datasource:
    url: jdbc:mysql://mysql:3306/appdb
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  mode: test

aws:
  region: ap-northeast-1
  endpoint: http://localhost:9000
  s3:
    bucket: memo-bucket

logging:
  level:
    root: INFO
    com.example.project: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate: WARN
